### ISSUE TITLE
osTicket site crash after plugin install

### ISSUE THREAD

**Issue by evxjson** [clonemeagain/plugin-autocloser#12]
Hi!
After installing the latest version of the plugin my osTicket site went down completely. 

Problem seems to be in the config.php:
`return array_merge($global_settings, ...$config_groups);`

_PHP Parse error:  syntax error, unexpected '.' in config.php on line 217
Errors parsing config.php_

should be: 
`return array_merge($global_settings, $config_groups);`

Now the plugin gets installed and osTicket stays alive.

I will open a new issue regarding the next problem.

osTicket version: 1.10.1
/Anders

**Comment by clonemeagain** [comment]
PHP 5.6 was released in 2014 and introduces the variadic unpack operator. 
http://php.net/manual/en/functions.arguments.php#functions.variable-arg-list 
I kinda like it. :-) 
5.6 is a minimum requirement for osTicket 1.10, so it seemed ok. Are you having any other issues? I'd upgrade asap.

**Comment by clonemeagain** [comment]
Assuming resolved.

**Comment by evxjson** [comment]
Hi!
Sorry for late response. You are absolutely correct and we have now upgraded to latest PHP. Everything seems to be working fine now.

Best Regards

**Comment by clonemeagain** [comment]
No worries mate, cheers for the update.
