### ISSUE TITLE
[feature] could be made with demand refresh task event with crontab?

### ISSUE THREAD

**Issue by mckaygerhard** [clonemeagain/plugin-autocloser#19]
could be this made with the "on demand refresh" of normal task of osticket when each agent make a refresh of the dashboard?

reading the setup this plugin need configuraing a cron task with the call...

**Comment by clonemeagain** [comment]
Sure, just enable Autocron.

**Comment by clonemeagain** [comment]
Feel free to reopen this if that doesn't work.

**Comment by mckaygerhard** [comment]
ok i'll report feedback i'll test tonight
