### ISSUE TITLE
Error when editing plugin settings

### ISSUE THREAD

**Issue by adrianogoncalves** [clonemeagain/plugin-autocloser#22]
Hi,
While opening plugin settings, the "Auto-Reply Canned Response" field always come with no-reply option set, no matter what you select.

Best regards,

Adriano

**Comment by clonemeagain** [comment]
Hi, 

I've seen issues with plugin settings, the easiest fix was to delete the plugin config entirely, then start again. Frustrating, but it works. You don't have to delete the plugin files, just remove it from the admin interface, then re-install it and reconfigure. I recommend taking a screenshot to help reconfigure the plugin.

This is particularly critical if you've changed the number of option groups.

**Comment by adrianogoncalves** [comment]
It worked! Thanks!
