### ISSUE TITLE
[Feature Request] Only auto-close on certain status

### ISSUE THREAD

**Issue by JMCA2** [clonemeagain/plugin-autocloser#3]
It would be very useful if it was possible to have a setting to only automatically close tickets under certain status (for example, an Awaiting-Response custom status)

**Comment by clonemeagain** [comment]
Hmm, yes, I can see that. We don't do it ourselves, but yeah, I'll have a look.

**Comment by clonemeagain** [comment]
Rewritten to change "From Status" -> "To Status" in config, and in code, which is actually simpler! yay. 
https://github.com/clonemeagain/plugin-autocloser/commit/17377ef8eb0b864930000adc1ce2e709653ac149
https://github.com/clonemeagain/plugin-autocloser/commit/fa1891642a1c2317c0819eca54cd396b5087aa72
