### ISSUE TITLE
Can this be used with version osTicket v1.16.1, PHP 8.1.3, MySQL 8.0.28 and Apache 2.4.52

### ISSUE THREAD

**Issue by bismarkmd** [clonemeagain/plugin-autocloser#39]
I have an instance of osTicket v1.16.1 with PHP 8.1.3, MySQL 8.0.28 and Apache 2.4.52.
Can I safely install this plugin?
Thanks!

**Comment by logmsf** [comment]
Hey it appears that with the latest version of osTicket (v1.16.1), which is running on PHP8, this plugin returns a fatal error.

@clonemeagain, any plans to update the plugin :-) ?

**Comment by theking81** [comment]
Try using PHP version 8.0 not 8.1 and report back

**Comment by XKa-MSF-OCB** [comment]
@theking81 
Same fatal error with PHP 8.0.17:
`
[Thu Apr 21 07:18:19.450724 2022] [mpm_prefork:notice] [pid 21] AH00163: Apache/2.4.53 (Debian) PHP/8.0.17 configured -- resuming normal operations
[Thu Apr 21 07:18:19.450791 2022] [core:notice] [pid 21] AH00094: Command line: 'apache2 -D FOREGROUND'
[Thu Apr 21 07:19:19.544091 2022] [php:error] [pid 38] [client 127.0.0.1:41744] PHP Fatal error:  Declaration of CloserPlugin::uninstall() must be compatible with Plugin::uninstall(&$errors) in /var/www/html/include/plugins/autocloser/class.CloserPlugin.php on line 504
`
:(

**Comment by XKa-MSF-OCB** [comment]
Referring to similar error at https://github.com/clonemeagain/osticket-plugin-mentioner/issues/15

**Comment by XKa-MSF-OCB** [comment]
@clonemeagain 

Fatal errors seem to be suppressed (but not sure if a proper fix) with the following 2 amendments:

- changing the method signature at:
https://github.com/clonemeagain/plugin-autocloser/blob/cc986b6a6c687144dca258e42dea6e00eca126df/class.CloserPlugin.php#L504
... to:
```
function uninstall(&$errors) {
```

- changing the method signature at:
https://github.com/clonemeagain/plugin-autocloser/blob/cc986b6a6c687144dca258e42dea6e00eca126df/config.php#L34
... to:
```
function pre_save(&$config, &$errors) {
```

Hope this may help.

Thank you very much for providing this useful osTicket plugin. 👍🏽

**Comment by clonemeagain** [comment]
Cheers mate, I think perryk submitted that PR and it's merged now.
