### ISSUE TITLE
[bug] Closing immediately when overdue

### ISSUE THREAD

**Issue by JMCA2** [clonemeagain/plugin-autocloser#4]
I've noticed the tickets seems to be getting closed automatically when overdue and in Waiting-For-Reply status, even if the days established before auto-closing have not passed

**Comment by JMCA2** [comment]
Hmm...
However, other ticket open for many days past the established timeframe, has not been auto-closed.

**Comment by clonemeagain** [comment]
Hmm, irritating. Can you post a screenshot of your plugin config so I can replicate it?

**Comment by JMCA2** [comment]
Here it is: https://i.imgur.com/CKyRZ5w.png

Both auto-note and auto-reply are also enabled

**Comment by clonemeagain** [comment]
Thanks for posting the screenshot. I think I found the error.
Much better now.  Let me know how that works out for ya mate.

**Comment by JMCA2** [comment]
Looks good for now, thank you!
