### ISSUE TITLE
DB Error #1062 after osTicket Update

### ISSUE THREAD

**Issue by mastertera** [clonemeagain/plugin-autocloser#45]
Dear Support Team

Last Week we updated osTicket to the latest Version.
No we have some issues with the Ticket Closer Plug-In.
There are an DB Error #1062.
Ialready deleted the Plug-In and the last-run key in the Database. But it not help. This is the Error we got:

[INSERT INTO ost_config SET key = 'last-run', value = 1666005608, updated = NOW()] Duplicate entry 'last-run' for key 'namespace'<br /> <br /> ---- Backtrace ----<br /> #0 C:\inetpub\wwwroot\support\Include\mysqli.php(203): osTicket->logDBError('DB Error #1062', '[INSERT INTO o...')<br /> #1 C:\inetpub\wwwroot\support\Include\class.orm.php(3482): db_query('INSERT INTOos...', true, true)<br /> #2 C:\inetpub\wwwroot\support\Include\class.orm.php(658): MySqlExecutor->execute()<br /> #3 C:\inetpub\wwwroot\support\Include\class.config.php(176): VerySimpleModel->save(true)<br /> #4 C:\inetpub\wwwroot\support\Include\class.config.php(109): ConfigItem->save()<br /> #5 C:\inetpub\wwwroot\support\Include\class.config.php(119): Config->create('last-run', 1666005608)<br /> #6 C:\inetpub\wwwroot\support\Include\class.config.php(84): Config->update('last-run', 1666005608)<br /> #7 C:\inetpub\wwwroot\support\Include\plugins\autocloser\class.CloserPlugin.php(188): Config->set('last-run', 1666005608)<br /> #8 C:\inetpub\wwwroot\support\Include\plugins\autocloser\class.CloserPlugin.php(79): CloserPlugin->is_time_to_run(Object(CloserPluginConfig))<br /> #9 C:\inetpub\wwwroot\support\Include\plugins\autocloser\class.CloserPlugin.php(68): CloserPlugin->logans_run_mode()<br /> #10 C:\inetpub\wwwroot\support\Include\class.signal.php(98): CloserPlugin->{closure}(NULL, Array)<br /> #11 C:\inetpub\wwwroot\support\Include\class.cron.php(123): Signal::send('cron', NULL, Array)<br /> #12 C:\inetpub\wwwroot\support\Include\api.cron.php(19): Cron::run()<br /> #13 C:\inetpub\wwwroot\support\Include\api.cron.php(40): CronApiController->run()<br /> #14 C:\inetpub\wwwroot\support\api\cron.php(23): LocalCronApiController::call()<br /> #15 {main}

Version OS Ticket -> 1.17
MySQL Version -> 5.5.65
PHP Version -> 8.1.11

Thank you for your help

Best regards
Michael

**Comment by Kuschi** [comment]
We have the same issue here with 
Version OS Ticket -> 1.17
MySQL Version -> 5.7.37
PHP Version -> 8.0.20

For me it looks like that the namespace key in the DB is not set correctly. The plugin will create a new row with empty namespace and key "last-run" instead of updating the existing row with key "last-run".

**Comment by extent-ops** [comment]
private function is_time_to_run(PluginConfig $config) {
        // We can store arbitrary things in the config, like, when we ran this last:
        $last_run = $this->$config->get('last-run-closer');
        $now = Misc::dbtime(); // Never assume about time...
        $this->$config->set('last-run-closer', $now);

works for me

**Comment by pierromanu** [comment]
> ```
> private function is_time_to_run(PluginConfig $config) {
>     // We can store arbitrary things in the config, like, when we ran this last:
>     $last_run = $this->$config->get('last-run-closer');
>     $now = Misc::dbtime(); // Never assume about time...
>     $this->$config->set('last-run-closer', $now);
> ```
> 
> works for me

@extent-ops where do insert this?

**Comment by extent-ops** [comment]
https://github.com/clonemeagain/plugin-autocloser/blob/master/class.CloserPlugin.php#L184

**Comment by pierromanu** [comment]
Thx looks good to me too now

**Comment by extent-ops** [comment]
@pierromanu sorry but its not fixing anything, my bad, tomorrow will try to find some solution

**Comment by pierromanu** [comment]
well. It has worked for me. No more error since.

**Comment by mastertera** [comment]
Hi
So I do not have any message on the logs after change the class.CloserPlugin.php.
But It also do nothing, the Tickets are still in the same status as before...

Thanks for your fixing :-)

**Comment by extent-ops** [comment]
@pierromanu @mastertera 

try this

[autocloser-patch.txt](https://github.com/clonemeagain/plugin-autocloser/files/9868439/autocloser-patch.txt)

**Comment by mastertera** [comment]
Hm... it still do nothing. This are my class-CloserPlugin.php
[class.CloserPlugin.txt](https://github.com/clonemeagain/plugin-autocloser/files/9868958/class.CloserPlugin.txt)

**Comment by extent-ops** [comment]
in is_time_to_run remove $this-> and check again

line 191    $last_run = $config->get('last-run');
line 193    $config->set('last-run', $now);

**Comment by mastertera** [comment]
Like this?

![image](https://user-images.githubusercontent.com/4169091/198035158-3c83c47f-5434-4ee3-91f3-25a3b86a33f2.png)

**Comment by extent-ops** [comment]
remove line 192

![image](https://user-images.githubusercontent.com/57215389/198039875-016bbddd-686a-4812-8ff5-3c52927c31c8.png)

**Comment by mastertera** [comment]
Im sorry, still no reaction :-( I User Task SCheduler from Windows, maybe this is handlet in a different way?

**Comment by extent-ops** [comment]
i am using linux, unfortunately I do not have any tickets now to close so i need to wait.
you can turn on DEBUG in class.CloserPlugin.php and then in php error log you will see more details, in my case i see that sql is executed fine:

![image](https://user-images.githubusercontent.com/57215389/198047010-fc3ad34d-7161-40b6-8e09-decac8898d31.png)

**Comment by mastertera** [comment]
I see the Plug-In runs, but the status of Tickets not changing:

php
CloserPlugin group [1]  has 0 open tickets.

php
Looking for tickets with query: 
SELECT ticket_id 
FROM ost_ticket WHERE lastupdate < DATE_SUB(NOW(), INTERVAL 7 DAY)
AND status_id=2  AND isanswered=1
ORDER BY ticket_id ASC
LIMIT 20

This is the configuration:
![image](https://user-images.githubusercontent.com/4169091/198055595-c9a3d15d-7954-40df-8405-1728b9b3f0cc.png)


Any Ideas?

**Comment by mastertera** [comment]
I just see, that the status_id=2 is always number 2. Also when I change the From Status it stays at ID 2

**Comment by mastertera** [comment]
Hi, has someone any News about my Case?

**Comment by philbertphotos** [comment]
my Bad change this $ins = "plugin.".$this->id.".instance.".$this->getInstances(8)->key['plugin_id'];
I hard coded "8" during testing this.
to This $ins = "plugin.".$this->id.".instance.".$this->getInstances($this->id)->key['plugin_id'];

basically it checks to see what version of Osticket is running and changes the namespace to match the instance.  The edited version I use works PERFECTLY :)

**Comment by nandi96** [comment]
@philbertphotos thanks, but for me, still not working.

The cron job ending without errors, but no ticket status changes.

Synology Cron:
/usr/local/bin/php80 /volume3/web/teszt171Rev1/ost/api/cron.php

Config:
![Képernyőkép 2022-11-16 163016](https://user-images.githubusercontent.com/97993114/202223376-1943277e-986e-4cf3-be85-b990b573f3c7.png)

**Comment by philbertphotos** [comment]
Need to see the PHP errorlog

**Comment by mastertera** [comment]
> Here you go.... there are a few other custom things where it logs some stuff in helpdesk but should not cause any issues.
> 
> [class.CloserPlugin.txt](https://github.com/clonemeagain/plugin-autocloser/files/10023147/class.CloserPlugin.txt)

This Version solved my Problem. But not instantly, I need to switch from 7 Days to 2. Then it worked. Now I can go back to 7 Days. Thank you for the solution :-)

**Comment by nandi96** [comment]
> Need to see the PHP errorlog

The log is empty...

**Comment by nandi96** [comment]
Now, it is working!

Question: How Can I modify the code for do this?

When an agent change the ticket status to "Accepted", add automatically a canned response.
OR
When an agent add a canned response to the ticket, after automatically change the ticket status.

The plugin do not need to look up the ticket age.
@philbertphotos @mastertera 

Thanks!

**Comment by JVC-MSF-OCB** [comment]
by the way we tried @philbertphotos solution but did not work for us.. is anyone else stuck with this too?
