### ISSUE TITLE
Require multiple status for selection in config

### ISSUE THREAD

**Issue by jighem** [clonemeagain/plugin-autocloser#7]
Require multiple "From Status" to be allowed for selection so that when any one of the selected status is there in the ticket then the autoclose function should be called.
please guide what can be done!

**Comment by clonemeagain** [comment]
Almost done on that mate, the new branch has this feature, still testing it. 

https://github.com/clonemeagain/plugin-autocloser/tree/feature/link-status-to-canned-response

**Comment by clonemeagain** [comment]
Ok, try upgrading to the latest version mate.
